import { z } from "zod";
import { apiErrorSchema, errorEnvelopeSchema, successEnvelopeSchema } from "./envelope.ts";
export const processingModes = ["workbench", "one-click"] as const;
export const taskStatuses = ["queued", "processing", "failed", "completed"] as const;
export const taskStages = ["upload", "parse", "scan", "rewrite", "export"] as const;
export const taskFailureCodes = ["queue_unavailable", "parse_failed", "scan_failed", "rewrite_failed", "export_failed", "worker_unavailable", "processing_timeout", "unexpected_worker_error"] as const;
export const taskDeletionReasons = ["user_requested", "expired"] as const;
export const processingModeSchema = z.enum(processingModes);
export const taskStatusSchema = z.enum(taskStatuses);
export const taskStageSchema = z.enum(taskStages);
export const taskFailureCodeSchema = z.enum(taskFailureCodes);
export const taskDeletionReasonSchema = z.enum(taskDeletionReasons);
export const uploadApiErrorCodeSchema = z.enum(["missing_file", "empty_file", "unsupported_extension", "mime_mismatch", "file_too_large", "missing_context", "rate_limited", "upload_unavailable", "csrf_invalid"]);
export const taskApiErrorCodeSchema = z.enum([...uploadApiErrorCodeSchema.options, "unauthorized_task_access", "task_not_found", "task_deleted", "task_expired", "task_delete_failed", "invalid_task_segment_query", "invalid_task_rewrite_query", "invalid_task_edit_history_query", "invalid_task_edit_operation", "invalid_task_feedback", "invalid_task_rollback", "risk_finding_not_found", "rewrite_option_not_found", "rollback_not_available", "task_edit_not_allowed"]);
export const uploadApiErrorSchema = apiErrorSchema.extend({ code: uploadApiErrorCodeSchema });
export const taskApiErrorSchema = apiErrorSchema.extend({ code: taskApiErrorCodeSchema });
export const taskFailureSchema = z.object({ taskId: z.string().min(1), code: taskFailureCodeSchema, stage: taskStageSchema, message: z.string().min(1), retryable: z.boolean(), nextStep: z.string().min(1) });
export const taskPollingSchema = z.object({ shouldPoll: z.boolean(), intervalMs: z.number().int().positive() });
export const uploadAcceptedDataSchema = z.object({ taskId: z.string().min(1), status: taskStatusSchema, stage: taskStageSchema, progressPercent: z.number().int().min(0).max(100), nextPath: z.string().startsWith("/tasks/"), mode: processingModeSchema, message: z.string().min(1), fileName: z.string().min(1) });
export const taskDeletedDataSchema = z.object({ taskId: z.string().min(1), deletedAt: z.string().datetime(), reason: taskDeletionReasonSchema, message: z.string().min(1), nextPath: z.string().startsWith("/") });
export const taskDetailDataSchema = z.object({ taskId: z.string().min(1), mode: processingModeSchema, status: taskStatusSchema, stage: taskStageSchema, progressPercent: z.number().int().min(0).max(100), statusMessage: z.string().min(1), nextStep: z.string().min(1), retryable: z.boolean(), isDelayed: z.boolean(), failure: taskFailureSchema.nullable(), poll: taskPollingSchema, fileName: z.string().min(1), mimeType: z.string().min(1), fileSize: z.number().int().nonnegative(), createdAt: z.string().datetime(), updatedAt: z.string().datetime(), accessScope: z.string().min(1), retentionDays: z.number().int().positive(), trainingUse: z.enum(["excluded"]) });
export const uploadAcceptedEnvelopeSchema = successEnvelopeSchema(uploadAcceptedDataSchema);
export const taskDeletedEnvelopeSchema = successEnvelopeSchema(taskDeletedDataSchema);
export const taskDetailEnvelopeSchema = successEnvelopeSchema(taskDetailDataSchema);
export const uploadErrorEnvelopeSchema = errorEnvelopeSchema(uploadApiErrorSchema);
export const taskErrorEnvelopeSchema = errorEnvelopeSchema(taskApiErrorSchema);
export type ProcessingMode = z.infer<typeof processingModeSchema>;
export type TaskStatus = z.infer<typeof taskStatusSchema>;
export type TaskStage = z.infer<typeof taskStageSchema>;
export type TaskFailureCode = z.infer<typeof taskFailureCodeSchema>;
export type TaskDeletionReason = z.infer<typeof taskDeletionReasonSchema>;
export type TaskFailure = z.infer<typeof taskFailureSchema>;
export type UploadApiErrorCode = z.infer<typeof uploadApiErrorCodeSchema>;
export type TaskApiErrorCode = z.infer<typeof taskApiErrorCodeSchema>;
export type UploadAcceptedData = z.infer<typeof uploadAcceptedDataSchema>;
export type TaskDeletedData = z.infer<typeof taskDeletedDataSchema>;
export type TaskDetailData = z.infer<typeof taskDetailDataSchema>;
export function isTerminalTaskStatus(status: TaskStatus) { return status === "failed" || status === "completed"; }